"""Fix role

Revision ID: c802d3034f36
Revises: 23dd7e123ac2
Create Date: 2023-12-25 14:24:29.916420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c802d3034f36'
down_revision: Union[str, None] = '23dd7e123ac2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_role_id_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_role_id_key', 'users', ['role_id'])
    # ### end Alembic commands ###
