"""Create new tables

Revision ID: 23b1b39f1ead
Revises: 201112f85dc3
Create Date: 2023-12-28 21:36:47.160591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23b1b39f1ead'
down_revision: Union[str, None] = '201112f85dc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groupTypes',
    sa.Column('groupType_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('customer_amount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('groupType_id')
    )
    op.create_table('timetables',
    sa.Column('timetable_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workout_date', sa.Date(), nullable=False),
    sa.Column('creation_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('timetable_id')
    )
    op.create_table('trainersCustomers',
    sa.Column('trainerCustomer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trainer_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('groupType_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['groupType_id'], ['groupTypes.groupType_id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('trainerCustomer_id')
    )
    op.create_table('trainersCustomers_timetables',
    sa.Column('trainerCustomer_timetable', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trainerCustomer_id', sa.Integer(), nullable=False),
    sa.Column('timetable_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['timetable_id'], ['timetables.timetable_id'], ),
    sa.ForeignKeyConstraint(['trainerCustomer_id'], ['trainersCustomers.trainerCustomer_id'], ),
    sa.PrimaryKeyConstraint('trainerCustomer_timetable')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trainersCustomers_timetables')
    op.drop_table('trainersCustomers')
    op.drop_table('timetables')
    op.drop_table('groupTypes')
    # ### end Alembic commands ###
